# Generated by Django 5.0.7 on 2026-03-26 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Remoção'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OUTRO', 'Outro')], max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
