# Generated by Django 5.0.7 on 2026-03-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='alteracoes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
