# Generated by Django 5.0.7 on 2025-12-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_docente_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turmadisciplina',
            unique_together=set(),
        ),
    ]
