# Generated by Django 5.0.7 on 2025-12-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_autorizacoes_pessoa_autorizada_buscar'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='telefone_secundario',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
