# Generated by Django 5.0.7 on 2026-01-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_nota_unique_together_nota_bimestre_nota_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropedagogico',
            name='trimestre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I Trimestre'), (2, 'II Trimestre'), (3, 'III Trimestre')], verbose_name='Trimestre'),
        ),
    ]
