# Generated by Django 5.0.7 on 2026-01-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_registropedagogico_trimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropedagogico',
            name='trimestre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I Trimestre'), (2, 'II Trimestre'), (3, 'III Trimestre'), (4, 'IV Trimestre')], verbose_name='Trimestre'),
        ),
    ]
