# Generated by Django 5.0.7 on 2026-01-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_registropedagogico_trimestre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroPedagogico',
        ),
    ]
