# Generated by Django 5.0.7 on 2026-01-08 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_registropedagogico'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.PositiveIntegerField(verbose_name='Ano Letivo')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, 'I Trimestre'), (2, 'II Trimestre'), (3, 'III Trimestre'), (4, 'IV Trimestre')], verbose_name='Trimestre')),
                ('observacoes', models.TextField(blank=True, help_text='Registro descritivo do desenvolvimento do aluno no trimestre', verbose_name='Observações Pedagógicas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pedagogicos', to='home.aluno', verbose_name='Aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pedagogicos', to='home.escola', verbose_name='Escola')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pedagogicos', to='home.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Registro Pedagógico',
                'verbose_name_plural': 'Registros Pedagógicos',
                'ordering': ['aluno', 'ano_letivo', 'trimestre'],
            },
        ),
        migrations.AddConstraint(
            model_name='registropedagogico',
            constraint=models.UniqueConstraint(fields=('aluno', 'turma', 'ano_letivo', 'trimestre'), name='unique_registro_pedagogico_trimestre'),
        ),
    ]
