# Generated by Django 5.0.7 on 2026-01-05 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_aluno_bolsa_familia_aluno_serie_ano_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chamada',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='turmadisciplina',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chamada',
            name='feita_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.docente'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='home.escola'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nota',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='tipo',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('responsavel', 'Responsável')], max_length=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('aluno', 'disciplina', 'turma', 'escola')},
        ),
        migrations.AddConstraint(
            model_name='chamada',
            constraint=models.UniqueConstraint(fields=('data', 'turma', 'disciplina'), name='unique_chamada_por_dia'),
        ),
    ]
