# Generated by Django 5.0.7 on 2026-01-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_registropedagogico_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroPedagogico',
        ),
    ]
