# Generated by Django 5.0.7 on 2026-01-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_chamada_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professores',
        ),
        migrations.AlterField(
            model_name='turmadisciplina',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.docente'),
        ),
        migrations.AlterUniqueTogether(
            name='turmadisciplina',
            unique_together={('turma', 'disciplina', 'professor')},
        ),
    ]
