# Generated by Django 5.0.7 on 2026-01-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_turma_professores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='bimestre',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Campo legado para compatibilidade de migrations antigas', null=True),
        ),
    ]
