# Generated by Django 5.0.7 on 2026-01-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_registropedagogico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='docente',
            name='grau_instrucao',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='docente',
            name='telefone_secundario',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='docente',
            name='bairro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AlterField(
            model_name='docente',
            name='cidade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='sexo',
            field=models.CharField(default='Masculino', max_length=20),
        ),
    ]
