# Generated by Django 5.0.7 on 2026-01-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_docente_ativo_remove_docente_disciplinas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
