# Generated by Django 5.0.7 on 2026-01-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_docente_ativo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nota',
            name='bimestre',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1º'), (2, '2º'), (3, '3º'), (4, '4º')], null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transporteescolar',
            name='usa_transporte_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='nota',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='media_anual',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='media_final',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota1',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota2',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota3',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota4',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='recuperacao',
        ),
    ]
