# Generated by Django 5.0.7 on 2026-01-21 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_nota_unique_together_nota_bimestre_nota_valor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporteescolar',
            name='usa_transporte_publico',
        ),
    ]
