# Generated by Django 5.0.7 on 2026-01-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_transporteescolar_usa_transporte_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteescolar',
            name='usa_transporte_publico',
            field=models.BooleanField(default=False),
        ),
    ]
