# Generated by Django 5.0.7 on 2026-01-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_nota_unique_together_nota_bimestre_nota_valor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
