# Generated by Django 5.0.7 on 2026-01-27 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_delete_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamada',
            name='criado_por',
        ),
        migrations.AddField(
            model_name='chamada',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamadas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiarioDeClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ministrada', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('resumo_conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_criados', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='home.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios_classe', to='home.escola')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios', to='home.docente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='home.turma')),
            ],
            options={
                'verbose_name': 'Diário de Classe',
                'verbose_name_plural': 'Diários de Classe',
                'ordering': ['-data_ministrada', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='chamada',
            name='diario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamada', to='home.diariodeclasse'),
        ),
    ]
