# Generated by Django 5.0.7 on 2026-02-08 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_chamada_feita_por_chamada_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariodeclasse',
            name='status',
            field=models.CharField(choices=[('PLANEJADA', 'Planejada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('INVALIDA', 'Inválida')], default='REALIZADA', max_length=10),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamadas_criadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
