# Generated by Django 5.0.7 on 2026-02-09 00:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_vincular_chamada_diario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamada',
            options={'verbose_name': 'Chamada', 'verbose_name_plural': 'Chamadas'},
        ),
        migrations.RemoveConstraint(
            model_name='chamada',
            name='unique_chamada_por_dia',
        ),
        migrations.RemoveField(
            model_name='chamada',
            name='data',
        ),
        migrations.RemoveField(
            model_name='chamada',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='chamada',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='chamada',
            name='turma',
        ),
        migrations.AddField(
            model_name='chamada',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamada',
            name='diario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chamada', to='home.diariodeclasse'),
        ),
    ]
