# Generated by Django 5.0.7 on 2026-02-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_tipoavaliacao_avaliacao_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='turma',
        ),
    ]
