# Generated by Django 5.0.7 on 2026-02-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_avaliacao_turma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='bimestre',
            field=models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')]),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('disciplina', 'bimestre', 'descricao', 'escola'), name='unique_avaliacao_por_disciplina_bimestre_escola'),
        ),
    ]
