# Generated by Django 5.0.7 on 2026-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_avaliacao_options_alter_avaliacao_bimestre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='tema',
            field=models.CharField(choices=[('legacy', 'Layout Antigo'), ('nucleo', 'Núcleo Escolar')], default='legacy', max_length=20),
        ),
    ]
