# Generated by Django 5.0.7 on 2026-03-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_escola_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='tema',
            field=models.CharField(choices=[('legacy', 'Escola Pequeno Aprendiz'), ('nucleo', 'Padrão Núcleo Escolar')], default='nucleo', max_length=20),
        ),
    ]
