# Generated by Django 5.0.7 on 2026-03-05 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_escola_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.PositiveIntegerField(verbose_name='Ano Letivo')),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(1, 'I Bimestre'), (2, 'II Bimestre'), (3, 'III Bimestre'), (4, 'IV Bimestre')], verbose_name='Bimestre')),
                ('observacoes', models.TextField(blank=True, help_text='Registro descritivo do desenvolvimento do aluno no bimestre', verbose_name='Observações Pedagógicas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_individuais', to='home.aluno', verbose_name='Aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_individuais', to='home.escola', verbose_name='Escola')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_individuais', to='home.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Relatório Individual',
                'verbose_name_plural': 'Relatórios Individuais',
                'ordering': ['aluno', 'ano_letivo', 'bimestre'],
            },
        ),
        migrations.DeleteModel(
            name='RegistroPedagogico',
        ),
        migrations.AddConstraint(
            model_name='relatorioindividual',
            constraint=models.UniqueConstraint(fields=('aluno', 'turma', 'ano_letivo', 'bimestre'), name='unique_relatorio_individual_bimestre'),
        ),
    ]
