# Generated by Django 5.0.7 on 2026-03-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_relatorioindividual_delete_registropedagogico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.PositiveIntegerField(verbose_name='Ano Letivo')),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(1, 'I Bimestre'), (2, 'II Bimestre'), (3, 'III Bimestre'), (4, 'IV Bimestre')], verbose_name='Bimestre')),
                ('observacoes', models.TextField(blank=True, help_text='Registro pedagógico da turma por disciplina no bimestre', verbose_name='Observações Pedagógicas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pedagogicos', to='home.disciplina', verbose_name='Disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pedagogicos', to='home.escola', verbose_name='Escola')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pedagogicos', to='home.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Registro Pedagógico',
                'verbose_name_plural': 'Registros Pedagógicos',
                'ordering': ['turma', 'disciplina', 'ano_letivo', 'bimestre'],
            },
        ),
        migrations.AddConstraint(
            model_name='registropedagogico',
            constraint=models.UniqueConstraint(fields=('turma', 'disciplina', 'ano_letivo', 'bimestre'), name='unique_registro_pedagogico_bimestre'),
        ),
    ]
