# Generated by Django 5.0.7 on 2026-03-05 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_registropedagogico_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presenca',
            name='status',
            field=models.CharField(choices=[('P', 'Presente'), ('F', 'Falta'), ('J', 'Falta Justificada')], db_index=True, default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='home.aluno'),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='chamada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='home.chamada'),
        ),
        migrations.AddConstraint(
            model_name='presenca',
            constraint=models.UniqueConstraint(fields=('chamada', 'aluno'), name='unique_presenca_chamada_aluno'),
        ),
    ]
