# Generated by Django 5.0.7 on 2026-03-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_presenca_unique_together_presenca_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='conceito',
            field=models.CharField(blank=True, choices=[('E', 'Evolução'), ('O', 'Ótimo'), ('B', 'Bom')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='sistema_avaliacao',
            field=models.CharField(choices=[('NUM', 'Numérica (nota)'), ('CON', 'Conceito (E/O/B)')], default='NUM', max_length=3),
        ),
    ]
