# Generated by Django 5.0.7 on 2026-03-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rename_chamada_feita_por_to_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='codigo_cliente',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
