# Generated by Django 5.0.7 on 2026-03-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_escola_codigo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='status',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=10),
        ),
    ]
