# Generated by Django 5.0.7 on 2026-03-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_turma_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='financeiro_ativo',
            field=models.BooleanField(default=False, verbose_name='Módulo financeiro ativo'),
        ),
    ]
