# Generated by Django 5.0.7 on 2026-03-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_escola_financeiro_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='recuperacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['disciplina', 'bimestre'], name='home_avalia_discipl_275a21_idx'),
        ),
    ]
