# Generated by Django 5.0.7 on 2026-03-16 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_nota_recuperacao_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='avaliacao',
            name='unique_avaliacao_por_disciplina_bimestre_escola',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='home.turma'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['turma', 'disciplina'], name='home_avalia_turma_i_71db13_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['escola', 'bimestre'], name='home_avalia_escola__a71bec_idx'),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('turma', 'disciplina', 'bimestre', 'descricao', 'escola'), name='unique_avaliacao_por_turma_disciplina_bimestre_escola'),
        ),
    ]
