# Generated by Django 5.0.7 on 2026-03-16 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_avaliacao_unique_avaliacao_por_disciplina_bimestre_escola_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_avaliacao', to='home.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_avaliacao', to='home.escola')),
            ],
        ),
    ]
