# Generated by Django 5.0.7 on 2026-03-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_modeloavaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='desconto_mensal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto automático aplicado nas mensalidades do aluno', max_digits=10),
        ),
    ]
