# Generated by Django 5.0.7 on 2026-03-17 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_aluno_desconto_mensal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['bimestre', 'data']},
        ),
        migrations.AddField(
            model_name='modeloavaliacao',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modeloavaliacao',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tipoavaliacao'),
        ),
        migrations.AlterField(
            model_name='modeloavaliacao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina'),
        ),
        migrations.AlterField(
            model_name='modeloavaliacao',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
    ]
