# Generated by Django 5.0.7 on 2026-03-17 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_aluno_desconto_mensal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['bimestre', 'data']},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='home.turma'),
        ),
    ]
