# Generated by Django 5.0.7 on 2026-03-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_avaliacao_options_modeloavaliacao_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('professor', 'Professor'), ('diretor', 'Diretor'), ('coordenador', 'Coordenador'), ('secretaria', 'Secretária'), ('responsavel', 'Responsável'), ('financeiro', 'Financeiro')], default='responsavel', max_length=20),
        ),
    ]
