# Generated by Django 5.0.7 on 2026-03-17 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_avaliacao_options_alter_avaliacao_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloavaliacao',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tipoavaliacao'),
        ),
        migrations.AlterField(
            model_name='modeloavaliacao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disciplina'),
        ),
        migrations.AlterField(
            model_name='modeloavaliacao',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
    ]
