# Generated by Django 5.0.7 on 2026-03-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_modeloavaliacao_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloavaliacao',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
