# Generated by Django 5.0.7 on 2026-03-17 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_modeloavaliacao_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='home.turma'),
        ),
    ]
