# Generated by Django 5.0.7 on 2026-03-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_userescola'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dia_vencimento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
