# Generated by Django 5.0.7 on 2026-04-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_avisopublico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoInfantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma')),
            ],
            options={
                'unique_together': {('aluno', 'turma', 'bimestre', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.avaliacaocategoria')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('O', 'Ótimo'), ('B', 'Bom'), ('E', 'Em evolução')], max_length=1)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.avaliacaoinfantil')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.avaliacaoitem')),
            ],
            options={
                'unique_together': {('avaliacao', 'item')},
            },
        ),
    ]
