# Generated by Django 5.0.7 on 2026-04-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_avaliacaocategoria_avaliacaoinfantil_avaliacaoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='tipo_turma',
            field=models.CharField(choices=[('INF', 'Infantil'), ('FUN', 'Fundamental'), ('MED', 'Médio')], default='FUN', max_length=3),
        ),
    ]
