# Generated by Django 5.0.7 on 2026-04-26 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_turma_tipo_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoitem',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='home.avaliacaocategoria'),
        ),
    ]
