# Generated by Django 5.0.7 on 2026-04-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_alter_avaliacaoitem_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacaoInfantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('texto', models.TextField(blank=True, default='')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma')),
            ],
            options={
                'unique_together': {('aluno', 'turma', 'bimestre', 'ano')},
            },
        ),
    ]
