# Generated by Django 5.0.7 on 2026-04-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_observacaoinfantil'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('encerrado', models.BooleanField(default=False)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
