# Generated by Django 5.0.7 on 2026-04-30 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_anoletivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='home.anoletivo'),
        ),
    ]
