# Generated by Django 5.0.7 on 2026-05-01 19:38

import home.utils_core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_turma_ano_letivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default=home.utils_core.gerar_matricula_unica, max_length=20, unique=True),
        ),
    ]
