# Generated by Django 5.0.7 on 2026-06-02 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_boletim'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='home.anoletivo'),
        ),
    ]
