# Generated by Django 5.0.7 on 2026-07-04 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0061_boletim"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chamada",
            options={
                "ordering": ["-data", "turma__nome", "disciplina__nome"],
                "verbose_name": "Chamada",
                "verbose_name_plural": "Chamadas",
            },
        ),
        migrations.AddField(
            model_name="chamada",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="chamada",
            name="diario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamadas",
                to="home.diariodeclasse",
            ),
        ),
    ]
