# Generated by Django 5.0.7 on 2026-07-22 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_alter_chamada_options_chamada_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='data',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chamada',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='home.disciplina'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='home.escola'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamadas', to='home.docente'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='home.turma'),
        ),
        migrations.AddField(
            model_name='turma',
            name='coordenadores',
            field=models.ManyToManyField(blank=True, related_name='turmas_coordenadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamada',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='chamada',
            index=models.Index(fields=['data'], name='home_chamad_data_f0f39a_idx'),
        ),
        migrations.AddIndex(
            model_name='chamada',
            index=models.Index(fields=['turma', 'data'], name='home_chamad_turma_i_0621a5_idx'),
        ),
        migrations.AddIndex(
            model_name='chamada',
            index=models.Index(fields=['disciplina', 'data'], name='home_chamad_discipl_afd948_idx'),
        ),
        migrations.AddIndex(
            model_name='chamada',
            index=models.Index(fields=['escola', 'data'], name='home_chamad_escola__9c2a32_idx'),
        ),
        migrations.AddConstraint(
            model_name='chamada',
            constraint=models.UniqueConstraint(fields=('turma', 'disciplina', 'professor', 'data'), name='unique_chamada_por_turma_disciplina_professor_data'),
        ),
    ]
