# Generated by Django 5.0.7 on 2026-07-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_chamada_data_chamada_disciplina_chamada_escola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='polivalente',
            field=models.BooleanField(default=False, verbose_name='Chamada Polivalente'),
        ),
    ]
