# Generated by Django 5.0.7 on 2026-06-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_anoletivo_options_anoletivo_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='polivalente',
            field=models.BooleanField(default=False, verbose_name='Turma Polivalente'),
        ),
    ]
