from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0064_turma_polivalente"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""

            ------------------------------------------------------------------
            -- Tabela do ManyToMany Turma.coordenadores
            ------------------------------------------------------------------

            CREATE TABLE IF NOT EXISTS home_turma_coordenadores (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                turma_id bigint NOT NULL,
                user_id bigint NOT NULL
            );

            ------------------------------------------------------------------
            -- Constraint UNIQUE
            ------------------------------------------------------------------

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'home_turma_coordenadores_turma_id_user_id_c39a4e0a_uniq'
                ) THEN
                    ALTER TABLE home_turma_coordenadores
                    ADD CONSTRAINT home_turma_coordenadores_turma_id_user_id_c39a4e0a_uniq
                    UNIQUE (turma_id, user_id);
                END IF;
            END$$;

            ------------------------------------------------------------------
            -- FK turma
            ------------------------------------------------------------------

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'home_turma_coordenadores_turma_id_5271d354_fk_home_turma_id'
                ) THEN
                    ALTER TABLE home_turma_coordenadores
                    ADD CONSTRAINT home_turma_coordenadores_turma_id_5271d354_fk_home_turma_id
                    FOREIGN KEY (turma_id)
                    REFERENCES home_turma(id)
                    DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END$$;

            ------------------------------------------------------------------
            -- FK user
            ------------------------------------------------------------------

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'home_turma_coordenadores_user_id_27cb5378_fk_home_user_id'
                ) THEN
                    ALTER TABLE home_turma_coordenadores
                    ADD CONSTRAINT home_turma_coordenadores_user_id_27cb5378_fk_home_user_id
                    FOREIGN KEY (user_id)
                    REFERENCES home_user(id)
                    DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END$$;

            ------------------------------------------------------------------
            -- Índices da tabela ManyToMany
            ------------------------------------------------------------------

            CREATE INDEX IF NOT EXISTS home_turma_coordenadores_turma_id_5271d354
                ON home_turma_coordenadores(turma_id);

            CREATE INDEX IF NOT EXISTS home_turma_coordenadores_user_id_27cb5378
                ON home_turma_coordenadores(user_id);

            ------------------------------------------------------------------
            -- Índices da Chamada
            ------------------------------------------------------------------

            CREATE INDEX IF NOT EXISTS home_chamad_data_f0f39a_idx
                ON home_chamada(data);

            CREATE INDEX IF NOT EXISTS home_chamad_turma_i_0621a5_idx
                ON home_chamada(turma_id, data);

            CREATE INDEX IF NOT EXISTS home_chamad_discipl_afd948_idx
                ON home_chamada(disciplina_id, data);

            CREATE INDEX IF NOT EXISTS home_chamad_escola__9c2a32_idx
                ON home_chamada(escola_id, data);

            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
