# Generated by Django 5.0.7 on 2026-06-25 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_turma_polivalente'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamada',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='home.disciplina'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='home.escola'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamadas', to='home.docente'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='home.turma'),
        ),
    ]
