# Generated by Django 5.0.7 on 2026-08-05 11:42

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.utils import timezone


def sanear_chamadas_duplicadas(apps, schema_editor):
    """
    Antes de criar a constraint de unicidade, saneia chamadas
    duplicadas existentes na base.

    Regra:
    - Mantém a chamada de menor ID (registro oficial).
    - Marca as demais como excluídas logicamente.
    """

    Chamada = apps.get_model("home", "Chamada")

    grupos = (
        Chamada.objects.values(
            "turma_id",
            "disciplina_id",
            "professor_id",
            "data",
        )
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )

    agora = timezone.now()
    chamadas_para_atualizar = []

    for grupo in grupos:

        chamadas = list(
            Chamada.objects.filter(
                turma_id=grupo["turma_id"],
                disciplina_id=grupo["disciplina_id"],
                professor_id=grupo["professor_id"],
                data=grupo["data"],
            ).order_by("id")
        )

        # Mantém a primeira chamada (menor ID).
        # As demais tornam-se registros históricos.
        for chamada in chamadas[1:]:

            chamada.excluido = True
            chamada.data_exclusao = agora

            chamadas_para_atualizar.append(chamada)

    if chamadas_para_atualizar:

        Chamada.objects.bulk_update(
            chamadas_para_atualizar,
            [
                "excluido",
                "data_exclusao",
            ],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0065_reconcile_partial_0063"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamada",
            name="data_exclusao",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chamada",
            name="excluido",
            field=models.BooleanField(
                default=False,
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name="chamada",
            name="excluido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamadas_excluidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            sanear_chamadas_duplicadas,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="chamada",
            constraint=models.UniqueConstraint(
                fields=(
                    "turma",
                    "disciplina",
                    "professor",
                    "data",
                ),
                condition=models.Q(excluido=False),
                name="unique_chamada_ativa_por_turma_disciplina_professor_data",
            ),
        ),
    ]
