# Generated by Django 5.0.7 on 2026-08-05 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0065_reconcile_partial_0063"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamada",
            name="data_exclusao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chamada",
            name="excluido",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="chamada",
            name="excluido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamadas_excluidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="chamada",
            constraint=models.UniqueConstraint(
                fields=("turma", "disciplina", "professor", "data"),
                condition=models.Q(excluido=False),
                name="unique_chamada_ativa_por_turma_disciplina_professor_data",
            ),
        ),
    ]
