# Generated by Django 5.0.7 on 2026-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "home",
            "0066_remove_chamada_unique_chamada_por_turma_disciplina_professor_data_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aluno",
            options={"ordering": ["nome"]},
        ),
        migrations.AddField(
            model_name="aluno",
            name="nivel_modalidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Infantil", "Infantil"),
                    ("Fundamental I", "Fundamental I"),
                    ("Fundamental II", "Fundamental II"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="forma_acesso",
            field=models.CharField(
                blank=True,
                choices=[
                    ("matricula", "Matrícula"),
                    ("rematricula", "Rematrícula"),
                    ("transferencia", "Transferência"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="nome",
            field=models.CharField(db_index=True, default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="aluno",
            index=models.Index(
                fields=["escola", "nome"], name="home_aluno_escola__1f718d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aluno",
            index=models.Index(
                fields=["escola", "ativo"], name="home_aluno_escola__0f8d83_idx"
            ),
        ),
    ]
