# Generated by Django 5.0.7 on 2026-09-17 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0067_alter_aluno_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_matricula",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVA", "Ativa"),
                            ("CONCLUIDA", "Concluída"),
                            ("TRANSFERIDA", "Transferida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ATIVA",
                        max_length=20,
                    ),
                ),
                (
                    "observacao",
                    models.TextField(
                        blank=True,
                        default="",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True),
                ),
            ],
            options={
                "ordering": [
                    "-ano_letivo__ano",
                    "aluno__nome",
                ],
            },
        ),
        # =========================================================
        # 🔹 CORREÇÃO DE ESTADO DA CHAMADA
        #
        # A constraint antiga não existe fisicamente no banco.
        # Portanto:
        # - removemos do estado do Django;
        # - não executamos nenhum DROP CONSTRAINT no banco.
        # =========================================================
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="chamada",
                    name="unique_chamada_por_turma_disciplina_professor_data",
                ),
            ],
        ),
        migrations.AddField(
            model_name="matricula",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matriculas",
                to="home.aluno",
            ),
        ),
        migrations.AddField(
            model_name="matricula",
            name="ano_letivo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matriculas",
                to="home.anoletivo",
            ),
        ),
        migrations.AddField(
            model_name="matricula",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matriculas",
                to="home.turma",
            ),
        ),
        migrations.AddConstraint(
            model_name="matricula",
            constraint=models.UniqueConstraint(
                fields=(
                    "aluno",
                    "ano_letivo",
                ),
                name="unique_matricula_aluno_ano",
            ),
        ),
    ]
