# Generated by Django 5.0.7 on 2026-10-01 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_alter_matricula_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlocacaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(blank=True, max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('tipo_movimentacao', models.CharField(choices=[('matricula', 'Matrícula'), ('transferencia_turma', 'Transferência de turma'), ('alteracao_turno', 'Alteração de turno'), ('transferencia_turma_turno', 'Transferência de turma e turno'), ('remanejamento', 'Remanejamento'), ('outro', 'Outro')], max_length=40)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alocacoes', to='home.aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_alocacoes', to='home.anoletivo')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_alocacao_realizados', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_alunos', to='home.turma')),
            ],
            options={
                'verbose_name': 'Histórico de Alocação do Aluno',
                'verbose_name_plural': 'Históricos de Alocação dos Alunos',
                'ordering': ['-data_inicio', '-criado_em'],
            },
        ),
    ]
