# Generated by Django 5.0.7 on 2026-10-07 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_historicoalocacaoaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamada_id_original', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID original da chamada')),
                ('turma_nome', models.CharField(blank=True, default='', max_length=255, verbose_name='Turma')),
                ('disciplina_nome', models.CharField(blank=True, default='', max_length=255, verbose_name='Disciplina')),
                ('professor_nome', models.CharField(blank=True, default='', max_length=255, verbose_name='Professor')),
                ('data_chamada', models.DateField(blank=True, null=True, verbose_name='Data da chamada')),
                ('acao', models.CharField(choices=[('CRIADA', 'Chamada criada'), ('EXCLUIDA', 'Chamada excluída')], db_index=True, max_length=20, verbose_name='Ação')),
                ('total_alunos', models.PositiveIntegerField(default=0, verbose_name='Total de alunos')),
                ('total_presentes', models.PositiveIntegerField(default=0, verbose_name='Total de presentes')),
                ('total_faltas', models.PositiveIntegerField(default=0, verbose_name='Total de faltas')),
                ('total_justificadas', models.PositiveIntegerField(default=0, verbose_name='Total de faltas justificadas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('chamada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='home.chamada', verbose_name='Chamada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_chamadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Auditoria de chamada',
                'verbose_name_plural': 'Auditorias de chamadas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['acao', 'criado_em'], name='home_audito_acao_a7ebc4_idx'), models.Index(fields=['chamada_id_original'], name='home_audito_chamada_fce12c_idx')],
            },
        ),
    ]
