# Generated by Django 5.0.7 on 2026-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_auditoriachamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriachamada',
            name='usuario_nome',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do usuário'),
        ),
    ]
