# Generated by Django 5.0.7 on 2026-03-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('home', '0042_nota_recuperacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensalidade',
            options={'ordering': ['vencimento']},
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='home.escola'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mensalidade',
            unique_together={('aluno', 'mes_referencia', 'ano_referencia')},
        ),
        migrations.AddIndex(
            model_name='mensalidade',
            index=models.Index(fields=['escola'], name='financeiro__escola__7486f5_idx'),
        ),
        migrations.AddIndex(
            model_name='mensalidade',
            index=models.Index(fields=['status'], name='financeiro__status_b5344a_idx'),
        ),
        migrations.AddIndex(
            model_name='mensalidade',
            index=models.Index(fields=['vencimento'], name='financeiro__vencime_d1a537_idx'),
        ),
    ]
