# Generated by Django 5.0.7 on 2026-04-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoajuda',
            name='playlist_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoajuda',
            name='tipo',
            field=models.CharField(choices=[('video', 'Vídeo'), ('playlist', 'Playlist')], default='video', max_length=10),
        ),
    ]
